import 'controller/sign_up_banking_info_controller.dart';import 'package:flutter/material.dart';import 'package:vms/core/app_export.dart';import 'package:vms/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:vms/widgets/app_bar/appbar_title.dart';import 'package:vms/widgets/app_bar/custom_app_bar.dart';import 'package:vms/widgets/custom_elevated_button.dart';import 'package:vms/widgets/custom_text_form_field.dart';class SignUpBankingInfoScreen extends GetWidget<SignUpBankingInfoController> {const SignUpBankingInfoScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 25.h, vertical: 55.v), child: Column(children: [_buildPhase(), SizedBox(height: 45.v), _buildInputField(), SizedBox(height: 18.v), _buildInput(), SizedBox(height: 18.v), _buildInput1(), SizedBox(height: 18.v), _buildInput2(), SizedBox(height: 27.v), Align(alignment: Alignment.centerLeft, child: GestureDetector(onTap: () {onTapFrame();}, child: Row(children: [CustomImageView(imagePath: ImageConstant.imgPlusPrimary, height: 16.adaptSize, width: 16.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("msg_add_multiple_banks".tr, style: CustomTextStyles.labelLargePrimarySemiBold))]))), SizedBox(height: 42.v), CustomElevatedButton(text: "lbl_submit".tr, buttonStyle: CustomButtonStyles.fillPrimaryTL18, buttonTextStyle: CustomTextStyles.titleSmallWhiteA700, onPressed: () {onTapSubmit();}), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 82.v, leadingWidth: 60.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 28.h, top: 34.v, bottom: 16.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarTitle(text: "lbl_sign_up".tr, margin: EdgeInsets.only(top: 37.v, bottom: 14.v)), styleType: Style.bgShadow_1); } 
/// Section Widget
Widget _buildPhase() { return Padding(padding: EdgeInsets.only(right: 3.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 3.v, bottom: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_banking_information2".tr, style: CustomTextStyles.titleLargeInterGray90001), SizedBox(height: 11.v), Row(children: [Text("lbl_next2".tr, style: CustomTextStyles.bodyMediumGray90001), Padding(padding: EdgeInsets.only(left: 10.h), child: Text("lbl_profile_status".tr, style: theme.textTheme.bodyMedium))])])), SizedBox(height: 58.adaptSize, width: 58.adaptSize, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: SizedBox(height: 58.adaptSize, width: 58.adaptSize, child: CircularProgressIndicator(value: 0.5, strokeWidth: 6.h))), Align(alignment: Alignment.center, child: Text("lbl_3_of_4".tr, style: CustomTextStyles.bodyMediumPoppinsBluegray800))]))])); } 
/// Section Widget
Widget _buildInputField() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_bank_name".tr, style: theme.textTheme.titleSmall), SizedBox(height: 9.v), CustomTextFormField(controller: controller.nameController, hintText: "lbl_al_jannat".tr, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 10.v, 10.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgProfilecard, height: 16.adaptSize, width: 16.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 37.v), contentPadding: EdgeInsets.only(top: 10.v, right: 30.h, bottom: 10.v))]); } 
/// Section Widget
Widget _buildInput() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_account_title".tr, style: CustomTextStyles.titleSmallGray900_1), SizedBox(height: 9.v), CustomTextFormField(controller: controller.asharAtiquevalueController, hintText: "lbl_ashar_atique".tr)]); } 
/// Section Widget
Widget _buildInput1() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_account_number".tr, style: CustomTextStyles.titleSmallGray900_1), SizedBox(height: 9.v), CustomTextFormField(controller: controller.valueController, hintText: "lbl_03190106294217".tr)]); } 
/// Section Widget
Widget _buildInput2() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_iban".tr, style: CustomTextStyles.titleSmallGray900_1), SizedBox(height: 9.v), CustomTextFormField(controller: controller.pKMEZNvalueController, hintText: "msg_pk51mezn0003190106294217".tr, textInputAction: TextInputAction.done)]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the createCollectionsScreen when the action is triggered.
onTapFrame() { Get.toNamed(AppRoutes.createCollectionsScreen, ); } 
/// Navigates to the vendorProfileSubmittedOneScreen when the action is triggered.
onTapSubmit() { Get.toNamed(AppRoutes.vendorProfileSubmittedOneScreen, ); } 
 }
