import 'controller/create_location_controller.dart';import 'package:flutter/material.dart';import 'package:vms/core/app_export.dart';import 'package:vms/widgets/app_bar/appbar_leading_image.dart';import 'package:vms/widgets/app_bar/appbar_subtitle.dart';import 'package:vms/widgets/app_bar/custom_app_bar.dart';import 'package:vms/widgets/custom_drop_down.dart';import 'package:vms/widgets/custom_elevated_button.dart';import 'package:vms/widgets/custom_text_form_field.dart';class CreateLocationScreen extends GetWidget<CreateLocationController> {const CreateLocationScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildDiscard(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 23.v), child: Column(children: [SizedBox(height: 3.v), _buildTitleName(), SizedBox(height: 19.v), _buildTitleCountry(), SizedBox(height: 19.v), _buildTitleCity(), SizedBox(height: 18.v), _buildDescriptionAddress(), SizedBox(height: 18.v), _buildTitleStatus(), SizedBox(height: 58.v), CustomElevatedButton(text: "lbl_save_create".tr, onPressed: () {onTapSaveCreate();}), SizedBox(height: 16.v), CustomElevatedButton(text: "lbl_discard".tr, buttonStyle: CustomButtonStyles.fillOnPrimary)])))); } 
/// Section Widget
PreferredSizeWidget _buildDiscard() { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftBlueGray30001, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 10.v), onTap: () {onTapArrowLeft();}), title: AppbarSubtitle(text: "lbl_add_location".tr, margin: EdgeInsets.only(left: 92.h)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildTitleName() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_name".tr, style: theme.textTheme.titleSmall), SizedBox(height: 9.v), CustomTextFormField(controller: controller.nameController, hintText: "msg_e_g_beverly_center".tr)]); } 
/// Section Widget
Widget _buildTitleCountry() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_country".tr, style: theme.textTheme.titleSmall), SizedBox(height: 8.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 16.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownGray600, height: 16.adaptSize, width: 16.adaptSize)), hintText: "msg_select_the_country".tr, items: controller.createLocationModelObj.value.dropdownItemList!.value, borderDecoration: DropDownStyleHelper.outlineBlueGray, onChanged: (value) {controller.onSelected(value);})]); } 
/// Section Widget
Widget _buildTitleCity() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_city".tr, style: theme.textTheme.titleSmall), SizedBox(height: 8.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 16.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownGray600, height: 16.adaptSize, width: 16.adaptSize)), hintText: "lbl_select_the_city".tr, items: controller.createLocationModelObj.value.dropdownItemList1!.value, borderDecoration: DropDownStyleHelper.outlineBlueGray, onChanged: (value) {controller.onSelected1(value);})]); } 
/// Section Widget
Widget _buildDescriptionAddress() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_address".tr, style: theme.textTheme.titleSmall), SizedBox(height: 13.v), CustomTextFormField(controller: controller.addressController, hintText: "msg_enter_your_address".tr, textInputAction: TextInputAction.done, maxLines: 9, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 15.v), borderDecoration: TextFormFieldStyleHelper.outlineGrayBL8, fillColor: appTheme.whiteA700)]); } 
/// Section Widget
Widget _buildTitleStatus() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_status2".tr, style: theme.textTheme.titleSmall), SizedBox(height: 9.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 16.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownGray600, height: 16.adaptSize, width: 16.adaptSize)), hintText: "lbl_in_process".tr, items: controller.createLocationModelObj.value.dropdownItemList2!.value, borderDecoration: DropDownStyleHelper.outlineBlueGray, onChanged: (value) {controller.onSelected2(value);})]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the locationListScreen when the action is triggered.
onTapSaveCreate() { Get.toNamed(AppRoutes.locationListScreen, ); } 
 }
