import 'controller/verification_one_tab_container_controller.dart';import 'package:flutter/material.dart';import 'package:vms/core/app_export.dart';import 'package:vms/presentation/verification_one_page/verification_one_page.dart';import 'package:vms/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:vms/widgets/app_bar/custom_app_bar.dart';class VerificationOneTabContainerScreen extends GetWidget<VerificationOneTabContainerController> {const VerificationOneTabContainerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: double.maxFinite, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 46.v), Padding(padding: EdgeInsets.only(left: 25.h), child: Text("lbl_verification".tr, style: CustomTextStyles.titleLargeInterGray90001)), SizedBox(height: 13.v), Container(width: 232.h, margin: EdgeInsets.only(left: 25.h), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_we_have_sent_a_verification2".tr, style: theme.textTheme.bodyMedium), TextSpan(text: "lbl_change".tr, style: CustomTextStyles.bodyMediumPrimary_1)]), textAlign: TextAlign.left)), SizedBox(height: 32.v), _buildInputNumber(), SizedBox(height: 457.v, child: TabBarView(controller: controller.tabviewController, children: [VerificationOnePage(), VerificationOnePage(), VerificationOnePage()]))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 81.v, leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.fromLTRB(20.h, 12.v, 323.h, 11.v), onTap: () {onTapArrowLeft();}), styleType: Style.bgFill); } 
/// Section Widget
Widget _buildInputNumber() { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.only(left: 25.h, right: 31.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_verification_code".tr, style: theme.textTheme.titleSmall), SizedBox(height: 9.v), Container(height: 44.v, width: 314.h, margin: EdgeInsets.only(left: 5.h), child: TabBar(controller: controller.tabviewController, labelPadding: EdgeInsets.zero, labelColor: appTheme.gray90001, labelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w400), unselectedLabelColor: appTheme.gray90001, unselectedLabelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w800), indicator: BoxDecoration(color: appTheme.gray5001, borderRadius: BorderRadius.circular(8.h), border: Border.all(color: theme.colorScheme.primary, width: 1.h)), tabs: [Tab(child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(width: 44.adaptSize, padding: EdgeInsets.symmetric(horizontal: 18.h, vertical: 13.v), decoration: AppDecoration.outlineGray200014.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Text("lbl_1".tr)), Container(width: 44.adaptSize, margin: EdgeInsets.only(left: 10.h), padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 13.v), decoration: AppDecoration.outlineGray200014.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Text("lbl_2".tr))])), Tab(child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(width: 44.adaptSize, padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 13.v), decoration: AppDecoration.outlineGray200014.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Text("lbl_3".tr)), Container(width: 44.adaptSize, margin: EdgeInsets.only(left: 10.h), padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 13.v), decoration: AppDecoration.outlineGray200014.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Text("lbl_42".tr))])), Tab(child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(width: 44.adaptSize, padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 13.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Text("lbl5".tr)), Container(width: 44.adaptSize, margin: EdgeInsets.only(left: 10.h), padding: EdgeInsets.symmetric(horizontal: 18.h, vertical: 12.v), decoration: AppDecoration.outlineGray200014.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Text("lbl6".tr))]))]))]))); } 
/// Common widget
Widget _buildInput({required String inputText1, required String inputText2, }) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(width: 44.adaptSize, padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 13.v), decoration: AppDecoration.outlineGray200014.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Text(inputText1, style: CustomTextStyles.titleSmallExtraBold.copyWith(color: appTheme.gray90001))), Container(width: 44.adaptSize, margin: EdgeInsets.only(left: 10.h), padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 13.v), decoration: AppDecoration.outlineGray200014.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Text(inputText2, style: CustomTextStyles.titleSmallExtraBold.copyWith(color: appTheme.gray90001)))]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
