import 'controller/forget_password_controller.dart';import 'package:flutter/material.dart';import 'package:vms/core/app_export.dart';import 'package:vms/widgets/custom_elevated_button.dart';import 'package:vms/widgets/custom_text_form_field.dart';class ForgetPasswordScreen extends GetWidget<ForgetPasswordController> {const ForgetPasswordScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 25.h, vertical: 37.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.center, child: Text("lbl_forget_password".tr, style: theme.textTheme.headlineSmall)), SizedBox(height: 60.v), Text("lbl_reset_password".tr, style: CustomTextStyles.titleLargeInterGray90001), SizedBox(height: 14.v), Text("msg_enter_email_no".tr, style: theme.textTheme.bodyMedium), SizedBox(height: 35.v), _buildInputField(), SizedBox(height: 32.v), CustomElevatedButton(text: "lbl_reset".tr, rightIcon: Container(margin: EdgeInsets.only(left: 8.h), child: CustomImageView(imagePath: ImageConstant.imgMaterialsymbolsarrowbackrounded, height: 20.adaptSize, width: 20.adaptSize)), buttonStyle: CustomButtonStyles.fillPrimaryTL18, buttonTextStyle: CustomTextStyles.titleSmallWhiteA700, onPressed: () {onTapReset();}), Spacer(), SizedBox(height: 7.v), Align(alignment: Alignment.center, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("msg_remember_your_account".tr, style: theme.textTheme.bodyMedium), GestureDetector(onTap: () {onTapTxtSignIn();}, child: Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_sign_in".tr, style: CustomTextStyles.titleSmallBold)))]))])))); } 
/// Section Widget
Widget _buildInputField() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_email_phone_number".tr, style: theme.textTheme.titleSmall), SizedBox(height: 9.v), CustomTextFormField(controller: controller.phoneNumberController, hintText: "msg_asha_iq11_gmail_com".tr, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 10.v, 10.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgUserBlueGray30001, height: 16.adaptSize, width: 16.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 37.v), contentPadding: EdgeInsets.only(top: 10.v, right: 30.h, bottom: 10.v))]); } 
/// Navigates to the verificationOneTabContainerScreen when the action is triggered.
onTapReset() { Get.toNamed(AppRoutes.verificationOneTabContainerScreen, ); } 
/// Navigates to the signUpScreen when the action is triggered.
onTapTxtSignIn() { Get.toNamed(AppRoutes.signUpScreen, ); } 
 }
