import 'controller/create_payout_controller.dart';import 'package:flutter/material.dart';import 'package:vms/core/app_export.dart';import 'package:vms/widgets/app_bar/appbar_leading_image.dart';import 'package:vms/widgets/app_bar/appbar_subtitle.dart';import 'package:vms/widgets/app_bar/custom_app_bar.dart';import 'package:vms/widgets/custom_drop_down.dart';import 'package:vms/widgets/custom_elevated_button.dart';import 'package:vms/widgets/custom_radio_button.dart';import 'package:vms/widgets/custom_text_form_field.dart';class CreatePayoutScreen extends GetWidget<CreatePayoutController> {const CreatePayoutScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 26.v), child: Column(children: [_buildTitleVendorName(), SizedBox(height: 19.v), _buildTitleCurrency(), SizedBox(height: 18.v), _buildTitleAmount(), SizedBox(height: 18.v), _buildTitleTransferMethod(), SizedBox(height: 16.v), _buildCollectionType(), SizedBox(height: 5.v)])), bottomNavigationBar: _buildSaveCreate())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftBlueGray30001, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 10.v), onTap: () {onTapArrowLeft();}), title: AppbarSubtitle(text: "lbl_create_payout".tr, margin: EdgeInsets.only(left: 89.h)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildTitleVendorName() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_select_vendor_name".tr, style: theme.textTheme.titleSmall), SizedBox(height: 9.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 16.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownBlueGray30001, height: 16.adaptSize, width: 16.adaptSize)), hintText: "msg_select_vendor_name2".tr, items: controller.createPayoutModelObj.value.dropdownItemList!.value, onChanged: (value) {controller.onSelected(value);})]); } 
/// Section Widget
Widget _buildTitleCurrency() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_currency".tr, style: theme.textTheme.titleSmall), SizedBox(height: 8.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 16.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownBlueGray30001, height: 16.adaptSize, width: 16.adaptSize)), hintText: "lbl_pkr".tr, hintStyle: CustomTextStyles.bodyMediumGray90001, items: controller.createPayoutModelObj.value.dropdownItemList1!.value, onChanged: (value) {controller.onSelected1(value);})]); } 
/// Section Widget
Widget _buildTitleAmount() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_amount".tr, style: theme.textTheme.titleSmall), SizedBox(height: 9.v), CustomTextFormField(controller: controller.amountController, hintText: "lbl_0_00".tr, textInputAction: TextInputAction.done)]); } 
/// Section Widget
Widget _buildTitleTransferMethod() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_transfer_method".tr, style: theme.textTheme.titleSmall), SizedBox(height: 9.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 16.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownBlueGray30001, height: 16.adaptSize, width: 16.adaptSize)), hintText: "msg_select_payment_method".tr, items: controller.createPayoutModelObj.value.dropdownItemList2!.value, onChanged: (value) {controller.onSelected2(value);})]); } 
/// Section Widget
Widget _buildCollectionType() { return Obx(() => Column(children: [Padding(padding: EdgeInsets.only(left: 16.h, top: 16.v, right: 238.h), child: CustomRadioButton(text: "lbl_manual".tr, value: controller.createPayoutModelObj.value.radioList.value[0], groupValue: controller.radioGroup.value, onChange: (value) {controller.radioGroup.value = value;})), Padding(padding: EdgeInsets.fromLTRB(16.h, 17.v, 224.h, 17.v), child: CustomRadioButton(text: "lbl_schedule".tr, value: controller.createPayoutModelObj.value.radioList.value[1], groupValue: controller.radioGroup.value, onChange: (value) {controller.radioGroup.value = value;}))])); } 
/// Section Widget
Widget _buildSaveCreate() { return CustomElevatedButton(text: "lbl_save_create".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 24.v)); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
