import 'controller/orders_tab_container_controller.dart';import 'package:flutter/material.dart';import 'package:vms/core/app_export.dart';import 'package:vms/presentation/orders_page/orders_page.dart';import 'package:vms/widgets/app_bar/appbar_image.dart';import 'package:vms/widgets/app_bar/appbar_subtitle.dart';import 'package:vms/widgets/app_bar/custom_app_bar.dart';import 'package:vms/widgets/custom_bottom_bar.dart';import 'package:vms/widgets/custom_drop_down.dart';import 'package:vms/widgets/custom_elevated_button.dart';import 'package:vms/widgets/custom_icon_button.dart';class OrdersTabContainerScreen extends GetWidget<OrdersTabContainerController> {const OrdersTabContainerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 24.v), _buildCreateCollection(), SizedBox(height: 18.v), _buildSearch(), SizedBox(height: 16.v), _buildTabview(), SizedBox(height: 453.v, child: TabBarView(controller: controller.tabviewController, children: [OrdersPage(), OrdersPage(), OrdersPage()]))])), bottomNavigationBar: Padding(padding: EdgeInsets.symmetric(horizontal: 7.h), child: _buildBottomBar()))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 48.h, leading: Container(margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 10.v), padding: EdgeInsets.symmetric(horizontal: 3.h, vertical: 6.v), decoration: AppDecoration.fillWhiteA, child: AppbarImage(imagePath: ImageConstant.imgMegaphone)), title: AppbarSubtitle(text: "lbl_orders".tr, margin: EdgeInsets.only(left: 120.h)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildCreateCollection() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomElevatedButton(width: 140.h, text: "lbl_create_order".tr, leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgPlus, height: 16.adaptSize, width: 16.adaptSize)), onPressed: () {onTapCreateOrder();}), CustomIconButton(height: 36.adaptSize, width: 36.adaptSize, padding: EdgeInsets.all(10.h), child: CustomImageView(imagePath: ImageConstant.imgDownload))])); } 
/// Section Widget
Widget _buildSearch() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_orders_location".tr, style: theme.textTheme.titleSmall), SizedBox(height: 9.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 10.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownBlueGray30001, height: 16.adaptSize, width: 16.adaptSize)), hintText: "lbl_all_locations".tr, items: controller.ordersTabContainerModelObj.value.dropdownItemList!.value, borderDecoration: DropDownStyleHelper.outlineGray, filled: false, onChanged: (value) {controller.onSelected(value);})])); } 
/// Section Widget
Widget _buildTabview() { return Container(height: 38.v, width: 327.h, decoration: BoxDecoration(color: appTheme.gray10001, borderRadius: BorderRadius.circular(8.h)), child: TabBar(controller: controller.tabviewController, labelPadding: EdgeInsets.zero, labelColor: appTheme.whiteA700, labelStyle: TextStyle(fontSize: 12.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w500), unselectedLabelColor: appTheme.gray90001, unselectedLabelStyle: TextStyle(fontSize: 12.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w500), indicatorPadding: EdgeInsets.all(4.0.h), indicator: BoxDecoration(color: appTheme.gray90001, borderRadius: BorderRadius.circular(8.h)), tabs: [Tab(child: Text("lbl_today".tr)), Tab(child: Text("lbl_7_days".tr)), Tab(child: Text("lbl_30_days".tr))])); } 
/// Section Widget
Widget _buildBottomBar() { return CustomBottomBar(onChanged: (BottomBarEnum type) {}); } 
/// Navigates to the createOrderNoProductScreen when the action is triggered.
onTapCreateOrder() { Get.toNamed(AppRoutes.createOrderNoProductScreen, ); } 
 }
