import 'controller/create_product_inventory_shipping_controller.dart';import 'package:flutter/material.dart';import 'package:vms/core/app_export.dart';import 'package:vms/widgets/app_bar/appbar_leading_image.dart';import 'package:vms/widgets/app_bar/appbar_subtitle.dart';import 'package:vms/widgets/app_bar/custom_app_bar.dart';import 'package:vms/widgets/custom_checkbox_button.dart';import 'package:vms/widgets/custom_elevated_button.dart';import 'package:vms/widgets/custom_text_form_field.dart';class CreateProductInventoryShippingScreen extends GetWidget<CreateProductInventoryShippingController> {const CreateProductInventoryShippingScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(bottom: 5.v), child: Column(children: [_buildProductDetails(), SizedBox(height: 24.v), _buildVariants(), SizedBox(height: 16.v), Container(margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 19.v), decoration: AppDecoration.fillGray5001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_inventory".tr, style: CustomTextStyles.titleSmallGray900_1), SizedBox(height: 10.v), Text("msg_inventory_will_be".tr, style: CustomTextStyles.labelLargeBluegray30001), SizedBox(height: 10.v), _buildTrackQuantity()]), SizedBox(height: 17.v), _buildCheckboxSection(), SizedBox(height: 17.v), _buildSkuInput(), SizedBox(height: 17.v), _buildBarcodeInput(), SizedBox(height: 36.v)])), SizedBox(height: 16.v), CustomElevatedButton(text: "lbl_save_next".tr, margin: EdgeInsets.symmetric(horizontal: 24.h), onPressed: () {onTapSaveNext();}), SizedBox(height: 16.v), CustomElevatedButton(text: "lbl_back".tr, margin: EdgeInsets.symmetric(horizontal: 24.h), buttonStyle: CustomButtonStyles.fillGrayTL8, onPressed: () {onTapBack();})])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftBlueGray30001, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 10.v), onTap: () {onTapArrowLeft();}), title: AppbarSubtitle(text: "lbl_add_products".tr, margin: EdgeInsets.only(left: 91.h)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildProductDetails() { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h), decoration: AppDecoration.fillWhiteA, child: Row(crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(top: 25.v), child: Text("msg_product_pricing".tr, style: theme.textTheme.labelLarge)), Padding(padding: EdgeInsets.only(left: 9.h), child: SizedBox(height: 40.v, child: VerticalDivider(width: 3.h, thickness: 3.v, color: appTheme.gray200, indent: 25.h))), CustomImageView(imagePath: ImageConstant.imgBadgeCheck, height: 18.adaptSize, width: 18.adaptSize, margin: EdgeInsets.only(left: 8.h, top: 24.v)), Padding(padding: EdgeInsets.only(left: 6.h, top: 25.v), child: Text("lbl_variant_setting".tr, style: CustomTextStyles.titleSmallPrimary_1)), Padding(padding: EdgeInsets.only(left: 8.h), child: SizedBox(height: 40.v, child: VerticalDivider(width: 3.h, thickness: 3.v, color: appTheme.gray200, indent: 25.h))), Padding(padding: EdgeInsets.only(left: 8.h, top: 25.v), child: Text("lbl_shipping".tr, style: CustomTextStyles.labelLargeBluegray30001))])); } 
/// Section Widget
Widget _buildVariants() { return Container(width: 327.h, margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillGray5001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_variants".tr, style: CustomTextStyles.titleSmallGray900_1), SizedBox(height: 11.v), GestureDetector(onTap: () {onTapTxtAddoptionslikecolororsize();}, child: Text("msg_add_options_like".tr, style: CustomTextStyles.bodySmallPrimary12))])); } 
/// Section Widget
Widget _buildTrackQuantity() { return Obx(() => CustomCheckboxButton(text: "lbl_track_quantity".tr, value: controller.trackQuantity.value, padding: EdgeInsets.symmetric(vertical: 1.v), onChange: (value) {controller.trackQuantity.value = value;})); } 
/// Section Widget
Widget _buildCheckboxSection() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("lbl_quantity".tr, style: theme.textTheme.labelLarge)), Text("lbl_edit_locations".tr, style: CustomTextStyles.bodySmallPrimary12)]), SizedBox(height: 8.v), Column(children: [Divider(), SizedBox(height: 7.v), _buildWarehouseTitle(labelText: "lbl_warehouse_1".tr, zeroText: "lbl_0".tr), SizedBox(height: 8.v), _buildWarehouseTitle(labelText: "lbl_warehouse_1".tr, zeroText: "lbl_0".tr), SizedBox(height: 8.v), _buildWarehouseTitle(labelText: "lbl_warehouse_1".tr, zeroText: "lbl_0".tr)]), SizedBox(height: 16.v), Obx(() => CustomCheckboxButton(text: "msg_continue_selling".tr, value: controller.checkbox.value, padding: EdgeInsets.symmetric(vertical: 1.v), onChange: (value) {controller.checkbox.value = value;})), SizedBox(height: 16.v), Obx(() => CustomCheckboxButton(text: "msg_this_product_has".tr, value: controller.hasSkuOrBarcode.value, padding: EdgeInsets.symmetric(vertical: 1.v), onChange: (value) {controller.hasSkuOrBarcode.value = value;}))]); } 
/// Section Widget
Widget _buildSkuInput() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_sku_stock_keeping".tr, style: CustomTextStyles.labelLargeBluegray30001), SizedBox(height: 5.v), CustomTextFormField(controller: controller.inputController)]); } 
/// Section Widget
Widget _buildBarcodeInput() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_barcode_isbn_upc".tr, style: CustomTextStyles.labelLargeBluegray30001), SizedBox(height: 5.v), CustomTextFormField(controller: controller.inputController1, textInputAction: TextInputAction.done)]); } 
/// Common widget
Widget _buildWarehouseTitle({required String labelText, required String zeroText, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 11.v, bottom: 10.v), child: Text(labelText, style: CustomTextStyles.bodySmall12.copyWith(color: appTheme.blueGray30001))), Container(width: 145.h, padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 8.v), decoration: AppDecoration.outlineGray200014.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(zeroText, style: theme.textTheme.bodyMedium!.copyWith(color: appTheme.blueGray30001)), CustomImageView(imagePath: ImageConstant.imgArrowup, height: 16.adaptSize, width: 16.adaptSize)]))]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the bottomMenuScreen when the action is triggered.
onTapTxtAddoptionslikecolororsize() { Get.toNamed(AppRoutes.bottomMenuScreen, ); } 
/// Navigates to the createProductVariantsScreen when the action is triggered.
onTapSaveNext() { Get.toNamed(AppRoutes.createProductVariantsScreen, ); } 
/// Navigates to the createProductProductInfoTabContainerScreen when the action is triggered.
onTapBack() { Get.toNamed(AppRoutes.createProductProductInfoTabContainerScreen, ); } 
 }
