import 'controller/sign_up_controller.dart';import 'package:flutter/material.dart';import 'package:vms/core/app_export.dart';import 'package:vms/widgets/app_bar/appbar_title.dart';import 'package:vms/widgets/app_bar/custom_app_bar.dart';import 'package:vms/widgets/custom_elevated_button.dart';import 'package:vms/widgets/custom_outlined_button.dart';class SignUpScreen extends GetWidget<SignUpController> {const SignUpScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 25.h, vertical: 45.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_get_onboard".tr, style: CustomTextStyles.titleLargeInterGray90001)), SizedBox(height: 14.v), Align(alignment: Alignment.centerLeft, child: Text("msg_create_your_account".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 32.v), CustomElevatedButton(text: "msg_continue_with_email".tr, rightIcon: Container(margin: EdgeInsets.only(left: 8.h), child: CustomImageView(imagePath: ImageConstant.imgMaterialsymbolsarrowbackrounded, height: 20.adaptSize, width: 20.adaptSize)), buttonStyle: CustomButtonStyles.fillPrimaryTL18, buttonTextStyle: CustomTextStyles.titleSmallWhiteA700, onPressed: () {onTapContinueWithEmail();}), SizedBox(height: 16.v), CustomOutlinedButton(text: "msg_continue_with_phone".tr, buttonStyle: CustomButtonStyles.outlineGrayTL181, buttonTextStyle: theme.textTheme.titleSmall!), SizedBox(height: 27.v), _buildFrame(), SizedBox(height: 24.v), CustomOutlinedButton(text: "msg_sign_in_with_gmail".tr, leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgSocialIcon, height: 20.adaptSize, width: 20.adaptSize)), buttonStyle: CustomButtonStyles.outlineGrayTL18, buttonTextStyle: theme.textTheme.titleSmall!, onPressed: () {onTapSignInWithGmail();}), Spacer(), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("msg_already_have_an".tr, style: theme.textTheme.bodyMedium), GestureDetector(onTap: () {onTapTxtLogin();}, child: Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_login".tr, style: CustomTextStyles.titleSmallBold)))])])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 82.v, centerTitle: true, title: AppbarTitle(text: "lbl_sign_up".tr, margin: EdgeInsets.only(top: 37.v, bottom: 14.v)), styleType: Style.bgShadow_1); } 
/// Section Widget
Widget _buildFrame() { return Padding(padding: EdgeInsets.symmetric(horizontal: 8.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 6.v, bottom: 9.v), child: SizedBox(width: 137.h, child: Divider())), Text("lbl_or".tr, style: theme.textTheme.titleSmall), Padding(padding: EdgeInsets.only(top: 6.v, bottom: 9.v), child: SizedBox(width: 137.h, child: Divider()))])); } 
/// Navigates to the signUpBasicInfoScreen when the action is triggered.
onTapContinueWithEmail() { Get.toNamed(AppRoutes.signUpBasicInfoScreen, ); } 
/// Navigates to the signUpStoreInfoTabContainerScreen when the action is triggered.
onTapSignInWithGmail() { Get.toNamed(AppRoutes.signUpStoreInfoTabContainerScreen, ); } 
/// Navigates to the loginScreen when the action is triggered.
onTapTxtLogin() { Get.toNamed(AppRoutes.loginScreen, ); } 
 }
