import 'controller/create_product_variants_controller.dart';import 'package:flutter/material.dart';import 'package:vms/core/app_export.dart';import 'package:vms/widgets/app_bar/appbar_leading_image.dart';import 'package:vms/widgets/app_bar/appbar_subtitle.dart';import 'package:vms/widgets/app_bar/custom_app_bar.dart';import 'package:vms/widgets/custom_checkbox_button.dart';import 'package:vms/widgets/custom_elevated_button.dart';import 'package:vms/widgets/custom_outlined_button.dart';import 'package:vms/widgets/custom_search_view.dart';import 'package:vms/widgets/custom_switch.dart';import 'package:vms/widgets/custom_text_form_field.dart';class CreateProductVariantsScreen extends GetWidget<CreateProductVariantsController> {const CreateProductVariantsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(bottom: 5.v), child: Column(children: [_buildBody(), SizedBox(height: 24.v), _buildCollectionType(), SizedBox(height: 16.v), _buildSearchEngineListing(), SizedBox(height: 16.v), _buildProductStatus(), SizedBox(height: 19.v), _buildOnlineStore(), SizedBox(height: 17.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_markets".tr, style: CustomTextStyles.bodySmallGray60012))), SizedBox(height: 14.v), _buildMarkets(), SizedBox(height: 16.v), CustomElevatedButton(text: "lbl_save".tr, margin: EdgeInsets.symmetric(horizontal: 24.h)), SizedBox(height: 16.v), CustomElevatedButton(text: "lbl_back".tr, margin: EdgeInsets.symmetric(horizontal: 24.h), buttonStyle: CustomButtonStyles.fillGrayTL8, onPressed: () {onTapBack();})])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftBlueGray30001, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 10.v), onTap: () {onTapArrowLeft();}), title: AppbarSubtitle(text: "lbl_add_products".tr, margin: EdgeInsets.only(left: 91.h)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildBody() { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h), decoration: AppDecoration.fillWhiteA, child: Row(crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(top: 26.v), child: Text("msg_product_pricing".tr, style: theme.textTheme.labelLarge)), Padding(padding: EdgeInsets.only(left: 9.h), child: SizedBox(height: 40.v, child: VerticalDivider(width: 3.h, thickness: 3.v, color: appTheme.gray200, indent: 25.h))), Padding(padding: EdgeInsets.only(left: 8.h, top: 26.v), child: Text("lbl_variant_setting".tr, style: theme.textTheme.labelLarge)), Padding(padding: EdgeInsets.only(left: 8.h), child: SizedBox(height: 40.v, child: VerticalDivider(width: 3.h, thickness: 3.v, color: appTheme.gray200, indent: 25.h))), Container(width: 83.h, margin: EdgeInsets.only(left: 8.h, top: 24.v), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgBadgeCheck, height: 18.adaptSize, width: 18.adaptSize), Padding(padding: EdgeInsets.only(left: 6.h, top: 2.v), child: Text("lbl_shipping".tr, style: CustomTextStyles.titleSmallPrimary_1))]))])); } 
/// Section Widget
Widget _buildLabelHelper() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_weight".tr, style: CustomTextStyles.labelLargeBluegray30001), SizedBox(height: 4.v), Row(children: [Expanded(child: CustomTextFormField(controller: controller.valueController, hintText: "lbl_0_0".tr, hintStyle: CustomTextStyles.labelMediumGray90001, borderDecoration: TextFormFieldStyleHelper.outlineGrayTL10, filled: false)), CustomOutlinedButton(width: 58.h, text: "lbl_kg".tr, margin: EdgeInsets.only(left: 4.h), rightIcon: Container(margin: EdgeInsets.only(left: 10.h), child: CustomImageView(imagePath: ImageConstant.imgArrowup, height: 16.adaptSize, width: 16.adaptSize)), buttonStyle: CustomButtonStyles.outlineGrayTL10, buttonTextStyle: CustomTextStyles.labelMediumGray90001)])]); } 
/// Section Widget
Widget _buildTitle() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_country_region_of".tr, style: CustomTextStyles.bodySmall12), SizedBox(height: 4.v), CustomTextFormField(controller: controller.countryController, hintText: "lbl_pakistan".tr, hintStyle: CustomTextStyles.labelMediumGray90001, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 10.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgArrowup, height: 16.adaptSize, width: 16.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 36.v), contentPadding: EdgeInsets.only(left: 10.h, top: 11.v, bottom: 11.v), borderDecoration: TextFormFieldStyleHelper.outlineGrayTL10, filled: false)]); } 
/// Section Widget
Widget _buildCheckbox() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_harmonized_system".tr, style: CustomTextStyles.bodySmall12), SizedBox(height: 5.v), CustomSearchView(controller: controller.searchController, hintText: "msg_search_by_product".tr, hintStyle: theme.textTheme.labelMedium!, borderDecoration: SearchViewStyleHelper.outlineGrayTL10, filled: false), SizedBox(height: 16.v), Obx(() => CustomCheckboxButton(text: "msg_continue_selling".tr, value: controller.checkbox.value, padding: EdgeInsets.symmetric(vertical: 1.v), onChange: (value) {controller.checkbox.value = value;}))]); } 
/// Section Widget
Widget _buildCollectionType() { return Container(margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillGray5001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_shipping".tr, style: CustomTextStyles.titleSmallGray900_1)), SizedBox(height: 8.v), Align(alignment: Alignment.centerLeft, child: Obx(() => CustomCheckboxButton(alignment: Alignment.centerLeft, text: "msg_this_is_a_physical".tr, value: controller.isPhysicalProduct.value, padding: EdgeInsets.symmetric(vertical: 1.v), onChange: (value) {controller.isPhysicalProduct.value = value;}))), SizedBox(height: 18.v), _buildLabelHelper(), SizedBox(height: 8.v), Divider(), SizedBox(height: 9.v), _buildTitle(), SizedBox(height: 9.v), _buildCheckbox(), SizedBox(height: 16.v), Align(alignment: Alignment.centerLeft, child: Obx(() => CustomCheckboxButton(alignment: Alignment.centerLeft, text: "msg_this_product_has".tr, value: controller.hasSkuOrBarcode.value, padding: EdgeInsets.symmetric(vertical: 1.v), onChange: (value) {controller.hasSkuOrBarcode.value = value;})))])); } 
/// Section Widget
Widget _buildSearchEngineListing() { return Container(margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 15.v), decoration: AppDecoration.fillGray5001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("msg_search_engine_listing".tr, style: theme.textTheme.titleSmall)), Text("lbl_edit".tr, style: CustomTextStyles.titleSmallPrimary_1)]), SizedBox(height: 5.v), Container(width: 276.h, margin: EdgeInsets.only(right: 18.h), child: Text("msg_add_a_title_and".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodySmallGray60012.copyWith(height: 1.50)))])); } 
/// Section Widget
Widget _buildProductStatus() { return Container(width: 327.h, margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 17.v), decoration: AppDecoration.fillGray5001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_product_status".tr, style: CustomTextStyles.titleSmallGray900_1), SizedBox(height: 11.v), Row(children: [Obx(() => CustomSwitch(value: controller.isSelectedSwitch.value, onChange: (value) {controller.isSelectedSwitch.value = value;})), Padding(padding: EdgeInsets.only(left: 8.h, top: 2.v, bottom: 2.v), child: Text("lbl_set_active".tr, style: CustomTextStyles.labelLargePrimary))])])); } 
/// Section Widget
Widget _buildOnlineStore() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_publishing".tr, style: CustomTextStyles.titleSmallGray900_1), SizedBox(height: 17.v), Text("lbl_sales_channels".tr, style: CustomTextStyles.bodySmallGray60012), SizedBox(height: 14.v), Obx(() => CustomCheckboxButton(text: "lbl_online_store".tr, value: controller.onlineStore.value, padding: EdgeInsets.symmetric(vertical: 1.v), textStyle: CustomTextStyles.bodySmallGray60012, onChange: (value) {controller.onlineStore.value = value;})), SizedBox(height: 18.v), Obx(() => CustomCheckboxButton(text: "msg_facebook_instagram".tr, value: controller.check.value, textStyle: CustomTextStyles.bodySmallGray60012, onChange: (value) {controller.check.value = value;}))])); } 
/// Section Widget
Widget _buildMarkets() { return Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Obx(() => CustomCheckboxButton(alignment: Alignment.centerLeft, text: "msg_europe_international".tr, value: controller.markets.value, textStyle: CustomTextStyles.bodySmallGray60012, onChange: (value) {controller.markets.value = value;})))); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the createProductInventoryShippingScreen when the action is triggered.
onTapBack() { Get.toNamed(AppRoutes.createProductInventoryShippingScreen, ); } 
 }
