import 'controller/bottom_menu_one_controller.dart';import 'package:flutter/material.dart';import 'package:vms/core/app_export.dart';import 'package:vms/widgets/custom_drop_down.dart';import 'package:vms/widgets/custom_elevated_button.dart';import 'package:vms/widgets/custom_text_form_field.dart';class BottomMenuOneScreen extends GetWidget<BottomMenuOneController> {const BottomMenuOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 20.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 20.h, right: 20.h, bottom: 54.v), child: Column(children: [_buildFrameRow(), SizedBox(height: 23.v), Align(alignment: Alignment.centerLeft, child: Row(children: [CustomImageView(imagePath: ImageConstant.imgMapPin, height: 14.adaptSize, width: 14.adaptSize, margin: EdgeInsets.only(bottom: 3.v)), Padding(padding: EdgeInsets.only(left: 10.h), child: Text("lbl_beverly_center".tr, style: theme.textTheme.titleSmall))])), SizedBox(height: 21.v), Column(children: [_buildVariantColumn(), SizedBox(height: 38.v), _buildTitleColumn(), SizedBox(height: 17.v), _buildTitleColumn1(), SizedBox(height: 8.v), Divider(), SizedBox(height: 36.v), _buildTitleRow(), SizedBox(height: 9.v), _buildTitleColumn2(), SizedBox(height: 17.v), _buildTitleColumn3(), SizedBox(height: 8.v), Divider()]), SizedBox(height: 36.v), _buildTitleRow1(), SizedBox(height: 9.v), _buildTitleColumn4(), SizedBox(height: 17.v), _buildTitleColumn5(), SizedBox(height: 20.v), CustomElevatedButton(text: "lbl_done".tr, onPressed: () {onTapDone();})]))))])))); } 
/// Section Widget
Widget _buildFrameRow() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgBars, height: 20.adaptSize, width: 20.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h, top: 3.v), child: Text("msg_location_inventory".tr, style: CustomTextStyles.titleSmallPrimary)), Spacer(), CustomImageView(imagePath: ImageConstant.imgXSecondarycontainer, height: 20.adaptSize, width: 20.adaptSize)]); } 
/// Section Widget
Widget _buildVariantColumn() { return Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(right: 25.h), child: Row(children: [Text("lbl_variant".tr, style: theme.textTheme.labelLarge), Spacer(flex: 59), Text("lbl_price".tr, style: theme.textTheme.labelLarge), Spacer(flex: 40), Text("lbl_quantity".tr, style: theme.textTheme.labelLarge)]))), SizedBox(height: 8.v), Divider(), SizedBox(height: 7.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.symmetric(vertical: 8.v), child: Text("lbl_green".tr, style: CustomTextStyles.bodyMediumPrimary)), Spacer(), _buildInput(textValue1: "lbl_rs".tr, textValue2: "lbl_0_00".tr), Container(width: 101.h, margin: EdgeInsets.only(left: 16.h), padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 8.v), decoration: AppDecoration.outlineGray200014.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_0".tr, style: CustomTextStyles.bodySmall12), CustomImageView(imagePath: ImageConstant.imgArrowup, height: 16.adaptSize, width: 16.adaptSize)]))])]); } 
/// Section Widget
Widget _buildTitleColumn() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_sku_stock_keeping".tr, style: CustomTextStyles.labelLargeBluegray30001), SizedBox(height: 5.v), CustomTextFormField(controller: controller.inputController)]); } 
/// Section Widget
Widget _buildTitleColumn1() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_barcode_isbn_upc".tr, style: CustomTextStyles.labelLargeBluegray30001), SizedBox(height: 5.v), CustomTextFormField(controller: controller.inputController1)]); } 
/// Section Widget
Widget _buildTitleRow() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(top: 9.v, bottom: 8.v), child: Text("lbl_black".tr, style: CustomTextStyles.bodyMediumPrimary)), Spacer(), _buildInput(textValue1: "lbl_rs".tr, textValue2: "lbl_0_00".tr), Padding(padding: EdgeInsets.only(left: 16.h), child: CustomDropDown(width: 101.h, icon: Container(margin: EdgeInsets.fromLTRB(30.h, 9.v, 16.h, 9.v), child: CustomImageView(imagePath: ImageConstant.imgArrowup, height: 16.adaptSize, width: 16.adaptSize)), hintText: "lbl_0".tr, hintStyle: CustomTextStyles.bodySmall12, items: controller.bottomMenuOneModelObj.value.dropdownItemList!.value, onChanged: (value) {controller.onSelected(value);}))]); } 
/// Section Widget
Widget _buildTitleColumn2() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_sku_stock_keeping".tr, style: CustomTextStyles.labelLargeBluegray30001), SizedBox(height: 5.v), CustomTextFormField(controller: controller.inputController2)]); } 
/// Section Widget
Widget _buildTitleColumn3() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_barcode_isbn_upc".tr, style: CustomTextStyles.labelLargeBluegray30001), SizedBox(height: 5.v), CustomTextFormField(controller: controller.inputController3)]); } 
/// Section Widget
Widget _buildTitleRow1() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.symmetric(vertical: 8.v), child: Text("lbl_red".tr, style: CustomTextStyles.bodyMediumPrimary)), Spacer(), _buildInput(textValue1: "lbl_rs".tr, textValue2: "lbl_0_00".tr), Padding(padding: EdgeInsets.only(left: 16.h), child: CustomDropDown(width: 101.h, icon: Container(margin: EdgeInsets.fromLTRB(30.h, 9.v, 16.h, 9.v), child: CustomImageView(imagePath: ImageConstant.imgArrowup, height: 16.adaptSize, width: 16.adaptSize)), hintText: "lbl_0".tr, hintStyle: CustomTextStyles.bodySmall12, items: controller.bottomMenuOneModelObj.value.dropdownItemList1!.value, onChanged: (value) {controller.onSelected1(value);}))]); } 
/// Section Widget
Widget _buildTitleColumn4() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_sku_stock_keeping".tr, style: CustomTextStyles.labelLargeBluegray30001), SizedBox(height: 5.v), CustomTextFormField(controller: controller.inputController4)]); } 
/// Section Widget
Widget _buildTitleColumn5() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_barcode_isbn_upc".tr, style: CustomTextStyles.labelLargeBluegray30001), SizedBox(height: 5.v), CustomTextFormField(controller: controller.inputController5, textInputAction: TextInputAction.done)]); } 
/// Common widget
Widget _buildInput({required String textValue1, required String textValue2, }) { return Container(width: 101.h, padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 8.v), decoration: AppDecoration.outlineGray200014.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(children: [Text(textValue1, style: CustomTextStyles.bodySmall12.copyWith(color: appTheme.blueGray30001)), Padding(padding: EdgeInsets.only(left: 10.h), child: Text(textValue2, style: CustomTextStyles.bodySmall12.copyWith(color: appTheme.blueGray30001)))])); } 
/// Navigates to the createProductInventoryShippingOneScreen when the action is triggered.
onTapDone() { Get.toNamed(AppRoutes.createProductInventoryShippingOneScreen, ); } 
 }
