import 'controller/create_order_no_product_controller.dart';import 'package:flutter/material.dart';import 'package:vms/core/app_export.dart';import 'package:vms/widgets/app_bar/appbar_leading_image.dart';import 'package:vms/widgets/app_bar/appbar_subtitle.dart';import 'package:vms/widgets/app_bar/custom_app_bar.dart';import 'package:vms/widgets/custom_drop_down.dart';import 'package:vms/widgets/custom_elevated_button.dart';import 'package:vms/widgets/custom_search_view.dart';class CreateOrderNoProductScreen extends GetWidget<CreateOrderNoProductController> {const CreateOrderNoProductScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 1.v), child: Column(children: [_buildAddProductToast(), SizedBox(height: 17.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_products".tr, style: theme.textTheme.titleSmall))), SizedBox(height: 9.v), _buildFrame1(), SizedBox(height: 18.v), _buildSeventySeven(), SizedBox(height: 18.v), _buildLabelHelper(), SizedBox(height: 19.v), _buildDescription(), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftBlueGray30001, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 10.v), onTap: () {onTapArrowLeft();}), title: AppbarSubtitle(text: "lbl_create_order".tr, margin: EdgeInsets.only(left: 93.h)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildAddProductToast() { return Container(width: double.maxFinite, padding: EdgeInsets.all(8.h), decoration: AppDecoration.outlineBlack.copyWith(borderRadius: BorderRadiusStyle.customBorderBL6), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgInfoWhiteA700, height: 16.adaptSize, width: 16.adaptSize), Container(height: 13.v, width: 333.h, margin: EdgeInsets.only(left: 10.h), child: Stack(alignment: Alignment.bottomLeft, children: [Align(alignment: Alignment.topCenter, child: Container(height: 12.v, width: 333.h, decoration: BoxDecoration(border: Border(left: BorderSide(color: appTheme.whiteA700, width: 1.h))))), Align(alignment: Alignment.bottomLeft, child: Padding(padding: EdgeInsets.only(left: 16.h), child: Text("msg_add_a_product_to".tr, style: CustomTextStyles.bodySmallWhiteA700)))]))])); } 
/// Section Widget
Widget _buildFrame1() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomSearchView(controller: controller.searchController, hintText: "lbl_search_products".tr)), CustomElevatedButton(width: 75.h, text: "lbl_browse".tr, margin: EdgeInsets.only(left: 10.h), buttonTextStyle: CustomTextStyles.labelLargeWhiteA700, onPressed: () {onTapBrowse();})])); } 
/// Section Widget
Widget _buildSeventySeven() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_customer".tr, style: theme.textTheme.titleSmall)), SizedBox(height: 9.v), CustomSearchView(controller: controller.searchController1, hintText: "msg_search_customer".tr), SizedBox(height: 16.v), Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 17.v), decoration: AppDecoration.fillGray5001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_notes".tr, style: CustomTextStyles.titleSmallGray900_1), SizedBox(height: 6.v), Text("lbl_no_notes".tr, style: CustomTextStyles.bodySmallGray6000112)]), CustomImageView(imagePath: ImageConstant.imgEdit, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(bottom: 22.v))]))])); } 
/// Section Widget
Widget _buildLabelHelper() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_market".tr, style: CustomTextStyles.titleSmallGray900_1), Text("lbl_primary".tr, style: CustomTextStyles.labelLargeBluegray30001)]), SizedBox(height: 5.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 10.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownBlueGray30001, height: 16.adaptSize, width: 16.adaptSize)), hintText: "msg_pakistan_pkr_rs".tr, items: controller.createOrderNoProductModelObj.value.dropdownItemList!.value, borderDecoration: DropDownStyleHelper.outlineGray, filled: false, onChanged: (value) {controller.onSelected(value);})])); } 
/// Section Widget
Widget _buildDescription() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_payment".tr, style: theme.textTheme.titleSmall), SizedBox(height: 11.v), Container(decoration: AppDecoration.outlineGray20001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 11.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.customBorderBL6), child: Column(mainAxisSize: MainAxisSize.min, children: [Column(children: [_buildFrame(discountText: "lbl_sub_total".tr, rsCounterText: "lbl_rs_0_00".tr), SizedBox(height: 6.v), _buildFrame(discountText: "lbl_add_discount".tr, rsCounterText: "lbl_rs_0_00".tr)]), SizedBox(height: 7.v), _buildFrame(discountText: "msg_add_shipping_or".tr, rsCounterText: "lbl_rs_0_00".tr), SizedBox(height: 5.v), _buildFrame(discountText: "lbl_estimated_tax".tr, rsCounterText: "lbl_rs_0_00".tr), SizedBox(height: 57.v), _buildFrame(discountText: "lbl_total".tr, rsCounterText: "lbl_rs_0_00".tr)])))])); } 
/// Common widget
Widget _buildFrame({required String discountText, required String rsCounterText, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(discountText, style: theme.textTheme.labelMedium!.copyWith(color: appTheme.blueGray30001)), Text(rsCounterText, style: theme.textTheme.bodySmall!.copyWith(color: appTheme.blueGray30001))]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the createOrderWithProductScreen when the action is triggered.
onTapBrowse() { Get.toNamed(AppRoutes.createOrderWithProductScreen, ); } 
 }
