import 'controller/vendor_profile_submitted_two_controller.dart';import 'package:flutter/material.dart';import 'package:vms/core/app_export.dart';import 'package:vms/widgets/app_bar/appbar_image.dart';import 'package:vms/widgets/app_bar/appbar_leading_image.dart';import 'package:vms/widgets/app_bar/appbar_subtitle.dart';import 'package:vms/widgets/app_bar/custom_app_bar.dart';import 'package:vms/widgets/custom_elevated_button.dart';class VendorProfileSubmittedTwoScreen extends GetWidget<VendorProfileSubmittedTwoController> {const VendorProfileSubmittedTwoScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.only(left: 25.h, top: 82.v, right: 25.h), child: Column(children: [_buildPhase(), SizedBox(height: 96.v), _buildTextAndSupporting(), SizedBox(height: 81.v), CustomElevatedButton(text: "lbl_dashboard".tr, buttonStyle: CustomButtonStyles.fillPrimaryTL18, buttonTextStyle: CustomTextStyles.titleSmallWhiteA700, onPressed: () {onTapDashboard();}), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 55.v, leadingWidth: 63.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgLogo3, margin: EdgeInsets.only(left: 24.h, top: 8.v, bottom: 8.v)), centerTitle: true, title: AppbarSubtitle(text: "lbl_ismmart".tr), actions: [Container(margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 15.v), padding: EdgeInsets.symmetric(horizontal: 3.h, vertical: 6.v), decoration: AppDecoration.fillWhiteA, child: AppbarImage(imagePath: ImageConstant.imgMegaphone))], styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildPhase() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(top: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_vendor_profile_submitted".tr, style: CustomTextStyles.titleLargeInterGray90001), SizedBox(height: 11.v), Row(children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text("lbl_status".tr, style: CustomTextStyles.bodyMediumGray90001)), Padding(padding: EdgeInsets.only(left: 10.h), child: Text("lbl_approved".tr, style: CustomTextStyles.bodyMediumTealA700))])]))), Container(height: 58.adaptSize, width: 58.adaptSize, margin: EdgeInsets.only(left: 13.h), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: SizedBox(height: 58.adaptSize, width: 58.adaptSize, child: CircularProgressIndicator(value: 0.5, strokeWidth: 6.h))), Align(alignment: Alignment.center, child: Text("lbl_4_of_4".tr, style: CustomTextStyles.bodyMediumPoppinsBluegray800))]))]); } 
/// Section Widget
Widget _buildTextAndSupporting() { return Container(padding: EdgeInsets.symmetric(horizontal: 26.h), child: Column(children: [Text("msg_vendor_profile_approved".tr, style: CustomTextStyles.titleMediumGray90001), SizedBox(height: 8.v), CustomImageView(imagePath: ImageConstant.imgCheckTealA700, height: 24.adaptSize, width: 24.adaptSize), SizedBox(height: 8.v), SizedBox(width: 270.h, child: Text("msg_proceed_forward".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.labelLargeGray600.copyWith(height: 1.50)))])); } 
/// Navigates to the vendorDashboardScreen when the action is triggered.
onTapDashboard() { Get.toNamed(AppRoutes.vendorDashboardScreen, ); } 
 }
