import 'controller/create_order_with_product_controller.dart';import 'package:flutter/material.dart';import 'package:vms/core/app_export.dart';import 'package:vms/widgets/app_bar/appbar_leading_image.dart';import 'package:vms/widgets/app_bar/appbar_subtitle.dart';import 'package:vms/widgets/app_bar/custom_app_bar.dart';import 'package:vms/widgets/custom_checkbox_button.dart';import 'package:vms/widgets/custom_drop_down.dart';import 'package:vms/widgets/custom_elevated_button.dart';import 'package:vms/widgets/custom_search_view.dart';import 'package:vms/widgets/custom_text_form_field.dart';class CreateOrderWithProductScreen extends GetWidget<CreateOrderWithProductController> {const CreateOrderWithProductScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 26.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 5.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_products".tr, style: theme.textTheme.titleSmall)), SizedBox(height: 9.v), _buildFrame(), SizedBox(height: 16.v), _buildProductCard(), SizedBox(height: 18.v), _buildTitle(), SizedBox(height: 16.v), _buildCollectionType(), SizedBox(height: 18.v), _buildFrame1(), SizedBox(height: 5.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 10.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownBlueGray30001, height: 16.adaptSize, width: 16.adaptSize)), hintText: "msg_pakistan_pkr_rs".tr, items: controller.createOrderWithProductModelObj.value.dropdownItemList!.value, borderDecoration: DropDownStyleHelper.outlineGray, filled: false, onChanged: (value) {controller.onSelected(value);}), SizedBox(height: 19.v), _buildPaymentDueLater()]))))])), bottomNavigationBar: _buildSaveCreate())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftBlueGray30001, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 10.v), onTap: () {onTapArrowLeft();}), title: AppbarSubtitle(text: "lbl_create_order".tr, margin: EdgeInsets.only(left: 93.h)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildFrame() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomSearchView(controller: controller.searchController, hintText: "lbl_search_products".tr)), CustomElevatedButton(width: 75.h, text: "lbl_browse".tr, margin: EdgeInsets.only(left: 10.h), buttonTextStyle: CustomTextStyles.labelLargeWhiteA700)]); } 
/// Section Widget
Widget _buildProductCard() { return Container(decoration: AppDecoration.fillGray5001, child: Container(padding: EdgeInsets.all(8.h), decoration: AppDecoration.outlineBlack900.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgDummyProduct, height: 40.adaptSize, width: 40.adaptSize, radius: BorderRadius.circular(10.h), margin: EdgeInsets.only(bottom: 90.v)), Expanded(child: Padding(padding: EdgeInsets.only(left: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_nike_360".tr, style: CustomTextStyles.labelLargePrimarySemiBold), CustomImageView(imagePath: ImageConstant.imgX, height: 16.adaptSize, width: 16.adaptSize)]), SizedBox(height: 4.v), Text("lbl_nike_store".tr, style: CustomTextStyles.labelMediumGray90001), SizedBox(height: 3.v), Text("lbl_sku_air360".tr, style: theme.textTheme.labelMedium), SizedBox(height: 3.v), Text("lbl_rs_9_000_00".tr, style: theme.textTheme.labelMedium), SizedBox(height: 15.v), Text("lbl_quantity".tr, style: CustomTextStyles.labelMediumGray90001), SizedBox(height: 2.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomTextFormField(width: 87.h, controller: controller.valueController, hintText: "lbl_2".tr, hintStyle: theme.textTheme.labelMedium!, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 8.v, 10.h, 8.v), child: CustomImageView(imagePath: ImageConstant.imgChevronsort, height: 16.adaptSize, width: 16.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 32.v), contentPadding: EdgeInsets.only(left: 10.h, top: 9.v, bottom: 9.v), borderDecoration: TextFormFieldStyleHelper.outlineGrayTL10, filled: false), Padding(padding: EdgeInsets.only(top: 16.v), child: Text("lbl_rs_18_000_00".tr, style: theme.textTheme.labelLarge))])])))]))); } 
/// Section Widget
Widget _buildTitle() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_customer".tr, style: theme.textTheme.titleSmall), SizedBox(height: 9.v), CustomSearchView(controller: controller.searchController1, hintText: "msg_search_customer2".tr)]); } 
/// Section Widget
Widget _buildCollectionType() { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 17.v), decoration: AppDecoration.fillGray5001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_notes".tr, style: CustomTextStyles.titleSmallGray900_1), SizedBox(height: 6.v), Text("lbl_no_notes".tr, style: CustomTextStyles.bodySmallGray6000112)]), CustomImageView(imagePath: ImageConstant.imgEdit, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(bottom: 22.v))])); } 
/// Section Widget
Widget _buildFrame1() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_market".tr, style: CustomTextStyles.titleSmallGray900_1), Text("lbl_primary".tr, style: CustomTextStyles.labelLargeBluegray30001)]); } 
/// Section Widget
Widget _buildPaymentDueLater() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_payment".tr, style: theme.textTheme.titleSmall), SizedBox(height: 11.v), Container(decoration: AppDecoration.outlineGray20001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 11.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.customBorderBL6), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildAddDiscount(discountText: "lbl_sub_total".tr, amountText: "lbl_rs_2_400".tr), SizedBox(height: 6.v), _buildAddDiscount(discountText: "lbl_add_discount".tr, amountText: "lbl_rs_240_02".tr), SizedBox(height: 7.v), Column(children: [_buildAddDiscount(discountText: "msg_add_shipping_or".tr, amountText: "lbl_rs_850".tr), SizedBox(height: 5.v), _buildAddDiscount(discountText: "lbl_estimated_tax".tr, amountText: "lbl_rs_1_790_00".tr)]), SizedBox(height: 56.v), _buildAddDiscount(discountText: "lbl_total".tr, amountText: "lbl_rs_0_00".tr)]))), SizedBox(height: 17.v), Obx(() => CustomCheckboxButton(text: "msg_payment_due_later".tr, value: controller.paymentDueLater.value, textStyle: CustomTextStyles.labelLargeBluegray30001, onChange: (value) {controller.paymentDueLater.value = value;}))]); } 
/// Section Widget
Widget _buildSaveCreate() { return CustomElevatedButton(text: "lbl_save_create".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 28.v), onPressed: () {onTapSaveCreate();}); } 
/// Common widget
Widget _buildAddDiscount({required String discountText, required String amountText, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(discountText, style: CustomTextStyles.labelMediumPrimary.copyWith(color: theme.colorScheme.primary)), Text(amountText, style: theme.textTheme.bodySmall!.copyWith(color: appTheme.blueGray30001))]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the ordersListScreen when the action is triggered.
onTapSaveCreate() { Get.toNamed(AppRoutes.ordersListScreen, ); } 
 }
