import 'controller/create_payout_one_controller.dart';import 'package:flutter/material.dart';import 'package:vms/core/app_export.dart';import 'package:vms/widgets/app_bar/appbar_leading_image.dart';import 'package:vms/widgets/app_bar/appbar_subtitle.dart';import 'package:vms/widgets/app_bar/custom_app_bar.dart';import 'package:vms/widgets/custom_drop_down.dart';import 'package:vms/widgets/custom_elevated_button.dart';import 'package:vms/widgets/custom_radio_button.dart';import 'package:vms/widgets/custom_text_form_field.dart';class CreatePayoutOneScreen extends GetWidget<CreatePayoutOneController> {const CreatePayoutOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 26.v), child: Column(children: [_buildTitleVendorName(), SizedBox(height: 19.v), _buildTitleCurrency(), SizedBox(height: 18.v), _buildTitleAmount(), SizedBox(height: 18.v), _buildTitleTransferMethod(), SizedBox(height: 16.v), _buildCollectionType(), SizedBox(height: 5.v)])), bottomNavigationBar: _buildSaveCreate())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftBlueGray30001, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 10.v), onTap: () {onTapArrowLeft();}), title: AppbarSubtitle(text: "lbl_create_payout".tr, margin: EdgeInsets.only(left: 89.h)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildTitleVendorName() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_select_vendor_name".tr, style: theme.textTheme.titleSmall), SizedBox(height: 9.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 16.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownBlueGray30001, height: 16.adaptSize, width: 16.adaptSize)), hintText: "lbl_vendor_name2".tr, hintStyle: CustomTextStyles.bodyMediumGray90001, items: controller.createPayoutOneModelObj.value.dropdownItemList!.value, onChanged: (value) {controller.onSelected(value);})]); } 
/// Section Widget
Widget _buildTitleCurrency() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_currency".tr, style: theme.textTheme.titleSmall), SizedBox(height: 8.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 16.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownBlueGray30001, height: 16.adaptSize, width: 16.adaptSize)), hintText: "lbl_pkr".tr, hintStyle: CustomTextStyles.bodyMediumGray90001, items: controller.createPayoutOneModelObj.value.dropdownItemList1!.value, onChanged: (value) {controller.onSelected1(value);})]); } 
/// Section Widget
Widget _buildTitleAmount() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_amount".tr, style: theme.textTheme.titleSmall), SizedBox(height: 9.v), CustomTextFormField(controller: controller.amountController, hintText: "lbl_54_987_00".tr, hintStyle: CustomTextStyles.bodyMediumGray90001, borderDecoration: TextFormFieldStyleHelper.outlineGrayTL10, filled: false)]); } 
/// Section Widget
Widget _buildTitleTransferMethod() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_transfer_method".tr, style: theme.textTheme.titleSmall), SizedBox(height: 9.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 16.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownBlueGray30001, height: 16.adaptSize, width: 16.adaptSize)), hintText: "lbl_bank_transfer".tr, hintStyle: CustomTextStyles.bodyMediumGray90001, items: controller.createPayoutOneModelObj.value.dropdownItemList2!.value, onChanged: (value) {controller.onSelected2(value);})]); } 
/// Section Widget
Widget _buildTitleTimeAndDate() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_time".tr, style: CustomTextStyles.labelMediumGray90001)), SizedBox(height: 7.v), Padding(padding: EdgeInsets.only(left: 24.h), child: CustomTextFormField(controller: controller.timeController, hintText: "lbl_15_30".tr, hintStyle: CustomTextStyles.bodySmallGray90001_1, textInputAction: TextInputAction.done, alignment: Alignment.centerRight, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 7.v)))]); } 
/// Section Widget
Widget _buildCollectionType() { return Container(padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillGray5001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Obx(() => CustomRadioButton(text: "lbl_manual".tr, value: "lbl_manual".tr, groupValue: controller.radioGroup.value, onChange: (value) {controller.radioGroup.value = value;})), SizedBox(height: 17.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgContrast, height: 19.v, width: 16.h), Padding(padding: EdgeInsets.only(left: 8.h, top: 2.v), child: Text("lbl_schedule".tr, style: CustomTextStyles.titleSmallGray900_1))]), SizedBox(height: 7.v), Padding(padding: EdgeInsets.only(left: 24.h), child: Text("msg_set_time_and_date".tr, style: CustomTextStyles.bodySmallGray6000112)), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_date".tr, style: CustomTextStyles.labelMediumGray90001)), SizedBox(height: 7.v), Padding(padding: EdgeInsets.only(left: 24.h), child: CustomTextFormField(controller: controller.dateController, hintText: "lbl_23_april_2023".tr, hintStyle: CustomTextStyles.bodySmallGray90001_1, alignment: Alignment.centerRight, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 7.v))), SizedBox(height: 3.v), _buildTitleTimeAndDate()])); } 
/// Section Widget
Widget _buildSaveCreate() { return CustomElevatedButton(text: "lbl_save_create".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 24.v)); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
