import 'controller/verification_controller.dart';import 'package:flutter/material.dart';import 'package:vms/core/app_export.dart';import 'package:vms/core/utils/validation_functions.dart';import 'package:vms/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:vms/widgets/app_bar/custom_app_bar.dart';import 'package:vms/widgets/custom_elevated_button.dart';import 'package:vms/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class VerificationScreen extends GetWidget<VerificationController> {VerificationScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 25.h, vertical: 49.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_update_password".tr, style: CustomTextStyles.titleLargeInterGray90001)), SizedBox(height: 12.v), Align(alignment: Alignment.centerLeft, child: Text("msg_set_your_new_password".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 34.v), _buildInputField1(), SizedBox(height: 18.v), _buildInputField2(), SizedBox(height: 32.v), CustomElevatedButton(text: "lbl_update".tr, buttonStyle: CustomButtonStyles.fillPrimaryTL18, buttonTextStyle: CustomTextStyles.titleSmallWhiteA700, onPressed: () {onTapUpdate();}), SizedBox(height: 5.v)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 81.v, leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.fromLTRB(20.h, 12.v, 323.h, 11.v), onTap: () {onTapArrowLeft();}), styleType: Style.bgFill); } 
/// Section Widget
Widget _buildInputField1() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_new_password".tr, style: theme.textTheme.titleSmall), SizedBox(height: 9.v), Obx(() => CustomTextFormField(controller: controller.newpasswordController, hintText: "lbl".tr, textInputType: TextInputType.visiblePassword, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 10.v, 10.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgLockBlueGray30001, height: 16.adaptSize, width: 16.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 37.v), suffix: InkWell(onTap: () {controller.isShowPassword.value = !controller.isShowPassword.value;}, child: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 16.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgEyeslashoutline, height: 16.adaptSize, width: 16.adaptSize))), suffixConstraints: BoxConstraints(maxHeight: 37.v), validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: controller.isShowPassword.value, contentPadding: EdgeInsets.symmetric(vertical: 10.v)))]); } 
/// Section Widget
Widget _buildInputField2() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_confirm_password".tr, style: theme.textTheme.titleSmall), SizedBox(height: 9.v), Obx(() => CustomTextFormField(controller: controller.confirmpasswordController, hintText: "lbl".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 10.v, 10.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgLockBlueGray30001, height: 16.adaptSize, width: 16.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 37.v), suffix: InkWell(onTap: () {controller.isShowPassword1.value = !controller.isShowPassword1.value;}, child: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 16.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgEyeslashoutline, height: 16.adaptSize, width: 16.adaptSize))), suffixConstraints: BoxConstraints(maxHeight: 37.v), validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: controller.isShowPassword1.value, contentPadding: EdgeInsets.symmetric(vertical: 10.v)))]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the passwordChangedScreen when the action is triggered.
onTapUpdate() { Get.toNamed(AppRoutes.passwordChangedScreen, ); } 
 }
