import 'controller/login_controller.dart';import 'package:flutter/material.dart';import 'package:vms/core/app_export.dart';import 'package:vms/core/utils/validation_functions.dart';import 'package:vms/widgets/app_bar/appbar_title.dart';import 'package:vms/widgets/app_bar/custom_app_bar.dart';import 'package:vms/widgets/custom_elevated_button.dart';import 'package:vms/widgets/custom_outlined_button.dart';import 'package:vms/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class LoginScreen extends GetWidget<LoginController> {LoginScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 25.h, vertical: 46.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_welcome_back".tr, style: CustomTextStyles.titleLargeInterGray90001)), SizedBox(height: 14.v), Align(alignment: Alignment.centerLeft, child: Text("msg_please_login_or".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 35.v), _buildInputField(), SizedBox(height: 18.v), _buildPasswordColumn(), SizedBox(height: 11.v), Align(alignment: Alignment.centerRight, child: GestureDetector(onTap: () {onTapTxtCaption();}, child: Text("msg_forget_password".tr, style: theme.textTheme.titleSmall))), SizedBox(height: 32.v), CustomElevatedButton(text: "lbl_login".tr, rightIcon: Container(margin: EdgeInsets.only(left: 8.h), child: CustomImageView(imagePath: ImageConstant.imgMaterialsymbolsarrowbackrounded, height: 20.adaptSize, width: 20.adaptSize)), buttonStyle: CustomButtonStyles.fillPrimaryTL18, buttonTextStyle: CustomTextStyles.titleSmallWhiteA700, onPressed: () {onTapLogin();}), SizedBox(height: 27.v), _buildFrame(), SizedBox(height: 24.v), CustomOutlinedButton(text: "msg_sign_in_with_gmail".tr, leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgSocialIcon, height: 20.adaptSize, width: 20.adaptSize)), buttonStyle: CustomButtonStyles.outlineGrayTL18, buttonTextStyle: theme.textTheme.titleSmall!, onPressed: () {onTapSignInWithGmail();}), Spacer(), Padding(padding: EdgeInsets.only(left: 27.h, right: 30.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("msg_don_t_have_an_account".tr, style: theme.textTheme.bodyMedium), GestureDetector(onTap: () {onTapTxtCreateAccount();}, child: Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_create_account".tr, style: CustomTextStyles.titleSmallBold)))]))]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 80.v, centerTitle: true, title: AppbarTitle(text: "lbl_login".tr)); } 
/// Section Widget
Widget _buildInputField() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_email_phone_number".tr, style: theme.textTheme.titleSmall), SizedBox(height: 9.v), CustomTextFormField(controller: controller.phoneNumberController, hintText: "lbl_03365563138".tr, textInputType: TextInputType.phone, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 10.v, 10.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgUserBlueGray30001, height: 16.adaptSize, width: 16.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 37.v), validator: (value) {if (!isValidPhone(value)) {return "err_msg_please_enter_valid_phone_number".tr;} return null;}, contentPadding: EdgeInsets.only(top: 10.v, right: 30.h, bottom: 10.v))]); } 
/// Section Widget
Widget _buildPasswordColumn() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_password".tr, style: theme.textTheme.titleSmall), SizedBox(height: 9.v), Obx(() => CustomTextFormField(controller: controller.passwordController, hintText: "lbl".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 10.v, 10.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgLockBlueGray30001, height: 16.adaptSize, width: 16.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 37.v), suffix: InkWell(onTap: () {controller.isShowPassword.value = !controller.isShowPassword.value;}, child: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 16.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgEyeslashoutline, height: 16.adaptSize, width: 16.adaptSize))), suffixConstraints: BoxConstraints(maxHeight: 37.v), validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: controller.isShowPassword.value, contentPadding: EdgeInsets.symmetric(vertical: 10.v)))]); } 
/// Section Widget
Widget _buildFrame() { return Padding(padding: EdgeInsets.symmetric(horizontal: 8.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 6.v, bottom: 9.v), child: SizedBox(width: 137.h, child: Divider())), Text("lbl_or".tr, style: theme.textTheme.titleSmall), Padding(padding: EdgeInsets.only(top: 6.v, bottom: 9.v), child: SizedBox(width: 137.h, child: Divider()))])); } 
/// Navigates to the forgetPasswordScreen when the action is triggered.
onTapTxtCaption() { Get.toNamed(AppRoutes.forgetPasswordScreen, ); } 
/// Navigates to the vendorDashboardScreen when the action is triggered.
onTapLogin() { Get.toNamed(AppRoutes.vendorDashboardScreen, ); } 
/// Navigates to the signUpStoreInfoTabContainerScreen when the action is triggered.
onTapSignInWithGmail() { Get.toNamed(AppRoutes.signUpStoreInfoTabContainerScreen, ); } 
/// Navigates to the signUpScreen when the action is triggered.
onTapTxtCreateAccount() { Get.toNamed(AppRoutes.signUpScreen, ); } 
 }
