import 'controller/create_product_product_info_controller.dart';import 'models/create_product_product_info_model.dart';import 'package:flutter/material.dart';import 'package:vms/core/app_export.dart';import 'package:vms/widgets/custom_checkbox_button.dart';import 'package:vms/widgets/custom_drop_down.dart';import 'package:vms/widgets/custom_elevated_button.dart';import 'package:vms/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class CreateProductProductInfoPage extends StatelessWidget {CreateProductProductInfoPage({Key? key}) : super(key: key);

CreateProductProductInfoController controller = Get.put(CreateProductProductInfoController(CreateProductProductInfoModel().obs));

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: _buildScrollViewSection())); } 
/// Section Widget
Widget _buildTitleSection() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_type2".tr, style: theme.textTheme.titleSmall), SizedBox(height: 8.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 16.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownBlueGray30001, height: 16.adaptSize, width: 16.adaptSize)), hintText: "msg_select_product_type".tr, items: controller.createProductProductInfoModelObj.value.dropdownItemList1!.value, onChanged: (value) {controller.onSelected1(value);})]); } 
/// Section Widget
Widget _buildCategorySection() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_category".tr, style: theme.textTheme.titleSmall), SizedBox(height: 8.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 16.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownBlueGray30001, height: 16.adaptSize, width: 16.adaptSize)), hintText: "msg_select_product_category".tr, items: controller.createProductProductInfoModelObj.value.dropdownItemList2!.value, onChanged: (value) {controller.onSelected2(value);})]); } 
/// Section Widget
Widget _buildTagsSection() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_tags".tr, style: theme.textTheme.titleSmall), SizedBox(height: 8.v), CustomTextFormField(controller: controller.searchController, hintText: "msg_assign_tags_for".tr, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 10.v, 10.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgSearchBlueGray30001, height: 16.adaptSize, width: 16.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 37.v), contentPadding: EdgeInsets.only(top: 10.v, right: 30.h, bottom: 10.v))]); } 
/// Section Widget
Widget _buildScrollViewSection() { return SingleChildScrollView(child: Column(children: [SizedBox(height: 18.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_price".tr, style: theme.textTheme.titleSmall)), SizedBox(height: 9.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 16.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 16.adaptSize, width: 16.adaptSize)), hintText: "lbl_0_00".tr, items: controller.createProductProductInfoModelObj.value.dropdownItemList!.value, borderDecoration: DropDownStyleHelper.outlineGray1, filled: false, onChanged: (value) {controller.onSelected(value);}), SizedBox(height: 19.v), _buildTitleSection(), SizedBox(height: 20.v), _buildCategorySection(), SizedBox(height: 20.v), _buildTagsSection(), SizedBox(height: 16.v), Align(alignment: Alignment.centerLeft, child: Obx(() => CustomCheckboxButton(alignment: Alignment.centerLeft, text: "msg_this_is_physical".tr, value: controller.check.value, padding: EdgeInsets.symmetric(vertical: 1.v), onChange: (value) {controller.check.value = value;}))), SizedBox(height: 16.v), CustomElevatedButton(text: "lbl_save_next".tr, onPressed: () {onTapSaveNext();}), SizedBox(height: 16.v), CustomElevatedButton(text: "lbl_back".tr, buttonStyle: CustomButtonStyles.fillGrayTL8, onPressed: () {onTapBack();})]))])); } 
/// Navigates to the createProductInventoryShippingScreen when the action is triggered.
onTapSaveNext() { Get.toNamed(AppRoutes.createProductInventoryShippingScreen, ); } 
/// Navigates to the productListScreen when the action is triggered.
onTapBack() { Get.toNamed(AppRoutes.productListScreen, ); } 
 }
