import '../product_list_screen/widgets/productlist_item_widget.dart';import 'controller/product_list_controller.dart';import 'models/productlist_item_model.dart';import 'package:flutter/material.dart';import 'package:vms/core/app_export.dart';import 'package:vms/widgets/app_bar/appbar_image.dart';import 'package:vms/widgets/app_bar/appbar_subtitle.dart';import 'package:vms/widgets/app_bar/custom_app_bar.dart';import 'package:vms/widgets/custom_bottom_bar.dart';import 'package:vms/widgets/custom_drop_down.dart';import 'package:vms/widgets/custom_elevated_button.dart';import 'package:vms/widgets/custom_icon_button.dart';class ProductListScreen extends GetWidget<ProductListController> {const ProductListScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 1.v), child: Column(children: [SizedBox(height: 23.v), _buildCreateCollection(), SizedBox(height: 16.v), _buildSearch(), SizedBox(height: 16.v), _buildPagination(), SizedBox(height: 25.v), SizedBox(height: 474.v, width: 311.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(top: 98.v), child: SizedBox(width: 311.h, child: Divider()))), _buildProductList()]))])), bottomNavigationBar: Padding(padding: EdgeInsets.symmetric(horizontal: 7.h), child: _buildBottomBar()))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 48.h, leading: Container(margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 10.v), padding: EdgeInsets.symmetric(horizontal: 3.h, vertical: 6.v), decoration: AppDecoration.fillWhiteA, child: AppbarImage(imagePath: ImageConstant.imgMegaphone)), title: AppbarSubtitle(text: "lbl_products".tr, margin: EdgeInsets.only(left: 111.h)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildCreateCollection() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomElevatedButton(width: 137.h, text: "lbl_add_product".tr, leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgPlus, height: 16.adaptSize, width: 16.adaptSize)), onPressed: () {onTapAddProduct();}), CustomIconButton(height: 36.adaptSize, width: 36.adaptSize, padding: EdgeInsets.all(10.h), child: CustomImageView(imagePath: ImageConstant.imgNotification))]); } 
/// Section Widget
Widget _buildSearch() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 10.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdown, height: 16.adaptSize, width: 16.adaptSize)), hintText: "lbl_all".tr, items: controller.productListModelObj.value.dropdownItemList!.value, borderDecoration: DropDownStyleHelper.outlineGray, filled: false, onChanged: (value) {controller.onSelected(value);})), Padding(padding: EdgeInsets.only(left: 8.h), child: CustomIconButton(height: 36.v, width: 62.h, padding: EdgeInsets.all(10.h), child: CustomImageView(imagePath: ImageConstant.imgSearch)))]); } 
/// Section Widget
Widget _buildPagination() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_1_20".tr, style: CustomTextStyles.bodySmall12), Padding(padding: EdgeInsets.only(left: 6.h), child: Text("lbl_of_50".tr, style: CustomTextStyles.bodySmall12)), Spacer(), CustomImageView(imagePath: ImageConstant.imgLeftRight, height: 12.adaptSize, width: 12.adaptSize, margin: EdgeInsets.only(top: 2.v)), CustomImageView(imagePath: ImageConstant.imgLeftRightBlueGray30001, height: 12.adaptSize, width: 12.adaptSize, margin: EdgeInsets.only(left: 6.h, top: 2.v))]); } 
/// Section Widget
Widget _buildProductList() { return Align(alignment: Alignment.center, child: Container(decoration: AppDecoration.outlineBlack9001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return Padding(padding: EdgeInsets.symmetric(vertical: 16.0.v), child: SizedBox(width: 311.h, child: Divider(height: 1.v, thickness: 1.v, color: appTheme.gray20001)));}, itemCount: controller.productListModelObj.value.productlistItemList.value.length, itemBuilder: (context, index) {ProductlistItemModel model = controller.productListModelObj.value.productlistItemList.value[index]; return ProductlistItemWidget(model);})))); } 
/// Section Widget
Widget _buildBottomBar() { return CustomBottomBar(onChanged: (BottomBarEnum type) {}); } 
/// Navigates to the createProductProductInfoTabContainerScreen when the action is triggered.
onTapAddProduct() { Get.toNamed(AppRoutes.createProductProductInfoTabContainerScreen, ); } 
 }
