import 'controller/create_product_product_info_tab_container_controller.dart';import 'package:flutter/material.dart';import 'package:vms/core/app_export.dart';import 'package:vms/core/utils/validation_functions.dart';import 'package:vms/presentation/create_product_product_info_page/create_product_product_info_page.dart';import 'package:vms/widgets/app_bar/appbar_leading_image.dart';import 'package:vms/widgets/app_bar/appbar_subtitle.dart';import 'package:vms/widgets/app_bar/custom_app_bar.dart';import 'package:vms/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class CreateProductProductInfoTabContainerScreen extends GetWidget<CreateProductProductInfoTabContainerController> {CreateProductProductInfoTabContainerScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Form(key: _formKey, child: SingleChildScrollView(child: Column(children: [_buildBody(), SizedBox(height: 26.v), _buildTitle(), SizedBox(height: 20.v), _buildDescription(), SizedBox(height: 18.v), _buildFileUpload(), _buildTabBarView()]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftBlueGray30001, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 10.v), onTap: () {onTapArrowLeft();}), title: AppbarSubtitle(text: "lbl_add_products".tr, margin: EdgeInsets.only(left: 91.h)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildBody() { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h), decoration: AppDecoration.fillWhiteA, child: Row(crossAxisAlignment: CrossAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgBadgeCheck, height: 18.adaptSize, width: 18.adaptSize, margin: EdgeInsets.only(top: 24.v)), Expanded(child: Padding(padding: EdgeInsets.only(left: 6.h, top: 24.v), child: Row(children: [Text("lbl_product_info".tr, style: CustomTextStyles.titleSmallPrimary_1), Padding(padding: EdgeInsets.only(left: 8.h), child: SizedBox(height: 16.v, child: VerticalDivider(width: 3.h, thickness: 3.v, color: appTheme.gray200, endIndent: 1.h))), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("msg_pricing_and_shipping".tr, style: CustomTextStyles.labelLargeBluegray30001)), Padding(padding: EdgeInsets.only(left: 8.h), child: SizedBox(height: 16.v, child: VerticalDivider(width: 3.h, thickness: 3.v, color: appTheme.gray200, endIndent: 1.h))), Padding(padding: EdgeInsets.only(left: 8.h, bottom: 1.v), child: Text("lbl_variants".tr, style: CustomTextStyles.labelLargeBluegray30001))])))])); } 
/// Section Widget
Widget _buildTitle() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_title".tr, style: theme.textTheme.titleSmall), SizedBox(height: 9.v), CustomTextFormField(controller: controller.nameController, hintText: "lbl_product_name".tr, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;})])); } 
/// Section Widget
Widget _buildDescription() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_description".tr, style: theme.textTheme.titleSmall), SizedBox(height: 11.v), Container(decoration: AppDecoration.outlineGray200013.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, children: [Container(padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 12.v), decoration: AppDecoration.fillGray10001.copyWith(borderRadius: BorderRadiusStyle.customBorderTL8), child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgPaperClip, height: 16.adaptSize, width: 16.adaptSize), CustomImageView(imagePath: ImageConstant.imgMapPin, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 15.h)), CustomImageView(imagePath: ImageConstant.imgFileImage, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 15.h)), CustomImageView(imagePath: ImageConstant.imgCode, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 15.h)), CustomImageView(imagePath: ImageConstant.imgFaceLaugh, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 15.h)), Padding(padding: EdgeInsets.only(left: 24.h), child: SizedBox(height: 16.v, child: VerticalDivider(width: 1.h, thickness: 1.v))), CustomImageView(imagePath: ImageConstant.imgList, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 23.h)), CustomImageView(imagePath: ImageConstant.imgCog, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 15.h)), CustomImageView(imagePath: ImageConstant.imgCalendarMonthBlueGray30001, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 15.h)), CustomImageView(imagePath: ImageConstant.imgDownloadBlueGray30001, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 15.h))])), CustomTextFormField(controller: controller.placeholderController, hintText: "msg_write_product_description".tr, textInputAction: TextInputAction.done, maxLines: 9, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 15.v), borderDecoration: TextFormFieldStyleHelper.fillWhiteA, fillColor: appTheme.whiteA700)]))])); } 
/// Section Widget
Widget _buildFileUpload() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_media".tr, style: theme.textTheme.titleSmall), SizedBox(height: 13.v), Container(height: 37.v, width: 327.h, child: TabBar(controller: controller.tabviewController, labelPadding: EdgeInsets.zero, labelColor: appTheme.gray90001, labelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w400), unselectedLabelColor: appTheme.gray5001, unselectedLabelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w500), indicator: BoxDecoration(color: appTheme.gray5001, borderRadius: BorderRadius.horizontal(right: Radius.circular(8.h)), border: Border.all(color: appTheme.gray20001, width: 1.h, strokeAlign: strokeAlignOutside)), tabs: [Tab(child: Text("lbl_choose_file".tr)), Tab(child: Text("lbl_no_file_chosen".tr))]))])); } 
/// Section Widget
Widget _buildTabBarView() { return SizedBox(height: 492.v, child: TabBarView(controller: controller.tabviewController, children: [CreateProductProductInfoPage(), CreateProductProductInfoPage()])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
