import 'controller/verification_link_controller.dart';import 'package:flutter/material.dart';import 'package:vms/core/app_export.dart';import 'package:vms/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:vms/widgets/app_bar/custom_app_bar.dart';import 'package:vms/widgets/custom_elevated_button.dart';class VerificationLinkScreen extends GetWidget<VerificationLinkController> {const VerificationLinkScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 25.h, vertical: 46.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_verification_link".tr, style: CustomTextStyles.titleLargeInterGray90001), SizedBox(height: 13.v), SizedBox(width: 186.h, child: Text("msg_we_sent_a_verification".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium!.copyWith(height: 1.50))), SizedBox(height: 32.v), Align(alignment: Alignment.center, child: Text("lbl_03_05".tr, style: CustomTextStyles.titleLargeInterSecondaryContainer)), SizedBox(height: 34.v), CustomElevatedButton(text: "lbl_back_to_login".tr, leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgMaterialsymbolsarrowbackroundedBlueGray50, height: 20.adaptSize, width: 20.adaptSize)), buttonStyle: CustomButtonStyles.fillPrimaryTL18, buttonTextStyle: CustomTextStyles.titleSmallWhiteA700), SizedBox(height: 18.v), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 28.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("msg_didn_t_receive_the".tr, style: theme.textTheme.bodyMedium), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_click_to_resend".tr, style: CustomTextStyles.titleSmallBold))]))), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 81.v, leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.fromLTRB(20.h, 12.v, 323.h, 11.v), onTap: () {onTapArrowLeft();}), styleType: Style.bgFill); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
