import 'controller/vendor_profile_submitted_controller.dart';import 'package:flutter/material.dart';import 'package:vms/core/app_export.dart';import 'package:vms/widgets/app_bar/appbar_image.dart';import 'package:vms/widgets/app_bar/appbar_leading_image.dart';import 'package:vms/widgets/app_bar/appbar_subtitle.dart';import 'package:vms/widgets/app_bar/custom_app_bar.dart';import 'package:vms/widgets/custom_elevated_button.dart';class VendorProfileSubmittedScreen extends GetWidget<VendorProfileSubmittedController> {const VendorProfileSubmittedScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.only(left: 25.h, top: 82.v, right: 25.h), child: Column(children: [_buildPhase(), SizedBox(height: 96.v), Text("msg_reason_for_rejection".tr, style: CustomTextStyles.titleMediumPrimary), SizedBox(height: 9.v), Container(width: 316.h, margin: EdgeInsets.symmetric(horizontal: 4.h), child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_due_to".tr, style: CustomTextStyles.labelLargeGray600_1), TextSpan(text: "msg_incomplete_information".tr, style: CustomTextStyles.labelLargeSecondaryContainer)]), textAlign: TextAlign.center)), SizedBox(height: 81.v), CustomElevatedButton(text: "lbl_request_again".tr, rightIcon: Container(margin: EdgeInsets.only(left: 8.h), child: CustomImageView(imagePath: ImageConstant.imgSettings, height: 16.adaptSize, width: 16.adaptSize)), buttonStyle: CustomButtonStyles.fillPrimaryTL18, buttonTextStyle: CustomTextStyles.titleSmallWhiteA700, onPressed: () {onTapRequestAgain();}), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 55.v, leadingWidth: 63.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgLogo3, margin: EdgeInsets.only(left: 24.h, top: 8.v, bottom: 8.v)), centerTitle: true, title: AppbarSubtitle(text: "lbl_ismmart".tr), actions: [Container(margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 15.v), padding: EdgeInsets.symmetric(horizontal: 3.h, vertical: 6.v), decoration: AppDecoration.fillWhiteA, child: AppbarImage(imagePath: ImageConstant.imgMegaphone))], styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildPhase() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(top: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_vendor_profile_submitted".tr, style: CustomTextStyles.titleLargeInterGray90001), SizedBox(height: 11.v), Row(children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text("lbl_status".tr, style: CustomTextStyles.bodyMediumGray90001)), Padding(padding: EdgeInsets.only(left: 10.h), child: Text("lbl_rejected".tr, style: CustomTextStyles.bodyMediumSecondaryContainer))])]))), Container(height: 58.adaptSize, width: 58.adaptSize, margin: EdgeInsets.only(left: 13.h), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: SizedBox(height: 58.adaptSize, width: 58.adaptSize, child: CircularProgressIndicator(value: 0.5, strokeWidth: 6.h))), Align(alignment: Alignment.center, child: Text("lbl_4_of_4".tr, style: CustomTextStyles.bodyMediumPoppinsBluegray800))]))]); } 
/// Navigates to the signUpBasicInfoScreen when the action is triggered.
onTapRequestAgain() { Get.toNamed(AppRoutes.signUpBasicInfoScreen, ); } 
 }
