import 'controller/create_product_inventory_shipping_one_controller.dart';import 'package:flutter/material.dart';import 'package:vms/core/app_export.dart';import 'package:vms/widgets/app_bar/appbar_leading_image.dart';import 'package:vms/widgets/app_bar/appbar_subtitle.dart';import 'package:vms/widgets/app_bar/custom_app_bar.dart';import 'package:vms/widgets/custom_checkbox_button.dart';import 'package:vms/widgets/custom_elevated_button.dart';import 'package:vms/widgets/custom_icon_button.dart';class CreateProductInventoryShippingOneScreen extends GetWidget<CreateProductInventoryShippingOneController> {const CreateProductInventoryShippingOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(bottom: 5.v), child: Column(children: [_buildBody(), SizedBox(height: 24.v), _buildVariants(), SizedBox(height: 16.v), _buildCollectionType(), SizedBox(height: 16.v), _buildCheckbox(), SizedBox(height: 16.v), _buildHasSkuOrBarcode(), SizedBox(height: 16.v), CustomElevatedButton(text: "lbl_save_next".tr, margin: EdgeInsets.symmetric(horizontal: 24.h), onPressed: () {onTapSaveNext();}), SizedBox(height: 16.v), CustomElevatedButton(text: "lbl_back".tr, margin: EdgeInsets.symmetric(horizontal: 24.h), buttonStyle: CustomButtonStyles.fillGrayTL8, onPressed: () {onTapBack();})])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftBlueGray30001, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 10.v), onTap: () {onTapArrowLeft();}), title: AppbarSubtitle(text: "lbl_add_products".tr, margin: EdgeInsets.only(left: 91.h)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildBody() { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h), decoration: AppDecoration.fillWhiteA, child: Row(crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(top: 25.v), child: Text("msg_product_pricing".tr, style: theme.textTheme.labelLarge)), Padding(padding: EdgeInsets.only(left: 9.h), child: SizedBox(height: 40.v, child: VerticalDivider(width: 3.h, thickness: 3.v, color: appTheme.gray200, indent: 25.h))), CustomImageView(imagePath: ImageConstant.imgBadgeCheck, height: 18.adaptSize, width: 18.adaptSize, margin: EdgeInsets.only(left: 8.h, top: 24.v)), Padding(padding: EdgeInsets.only(left: 6.h, top: 25.v), child: Text("lbl_variant_setting".tr, style: CustomTextStyles.titleSmallPrimary_1)), Padding(padding: EdgeInsets.only(left: 8.h), child: SizedBox(height: 40.v, child: VerticalDivider(width: 3.h, thickness: 3.v, color: appTheme.gray200, indent: 25.h))), Padding(padding: EdgeInsets.only(left: 8.h, top: 25.v), child: Text("lbl_shipping".tr, style: CustomTextStyles.labelLargeBluegray30001))])); } 
/// Section Widget
Widget _buildVariantsFrame() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_variants".tr, style: CustomTextStyles.titleSmallGray900_1), SizedBox(height: 10.v), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(left: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgReArrange, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(top: 12.v, bottom: 14.v)), Padding(padding: EdgeInsets.only(left: 10.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_color".tr, style: CustomTextStyles.bodySmallGray60012), SizedBox(height: 5.v), SizedBox(width: 134.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(width: 47.h, padding: EdgeInsets.symmetric(horizontal: 6.h, vertical: 3.v), decoration: AppDecoration.fillGray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Text("lbl_green".tr, style: CustomTextStyles.labelLargeBluegray700)), Container(width: 44.h, padding: EdgeInsets.symmetric(horizontal: 6.h, vertical: 3.v), decoration: AppDecoration.fillGray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Text("lbl_black".tr, style: CustomTextStyles.labelLargeBluegray700)), Container(width: 35.h, padding: EdgeInsets.symmetric(horizontal: 6.h, vertical: 3.v), decoration: AppDecoration.fillGray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Text("lbl_red".tr, style: CustomTextStyles.labelLargeBluegray700))]))])), Spacer(), Padding(padding: EdgeInsets.only(top: 2.v, bottom: 4.v), child: CustomIconButton(height: 36.adaptSize, width: 36.adaptSize, padding: EdgeInsets.all(10.h), onTap: () {onTapBtnEdit();}, child: CustomImageView(imagePath: ImageConstant.imgEdit)))])))]); } 
/// Section Widget
Widget _buildBlackVariants() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_black".tr, style: theme.textTheme.labelLarge), SizedBox(height: 11.v), SizedBox(width: 122.h, child: Text("msg_rs_350_00_25_available".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodySmall)), SizedBox(height: 16.v), Text("lbl_red".tr, style: theme.textTheme.labelLarge), SizedBox(height: 11.v), SizedBox(width: 123.h, child: Text("msg_rs_480_00_89_available".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodySmall))]); } 
/// Section Widget
Widget _buildVariants() { return Container(margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 15.v), decoration: AppDecoration.fillGray5001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), _buildVariantsFrame(), SizedBox(height: 16.v), Divider(), SizedBox(height: 17.v), Text("msg_showing_1_variant".tr, style: CustomTextStyles.bodySmallGray60012), SizedBox(height: 5.v), Text("lbl_green".tr, style: theme.textTheme.labelLarge), SizedBox(height: 11.v), SizedBox(width: 116.h, child: Text("msg_rs_450_00_5_available".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodySmall)), SizedBox(height: 16.v), _buildBlackVariants()])); } 
/// Section Widget
Widget _buildCollectionType() { return Container(margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 19.v), decoration: AppDecoration.fillGray5001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_inventory".tr, style: CustomTextStyles.titleSmallGray900_1)), SizedBox(height: 10.v), Align(alignment: Alignment.centerLeft, child: Text("msg_inventory_will_be".tr, style: CustomTextStyles.labelLargeBluegray30001)), SizedBox(height: 10.v), Align(alignment: Alignment.centerLeft, child: Obx(() => CustomCheckboxButton(alignment: Alignment.centerLeft, text: "lbl_track_quantity".tr, value: controller.trackQuantity.value, padding: EdgeInsets.symmetric(vertical: 1.v), onChange: (value) {controller.trackQuantity.value = value;}))), SizedBox(height: 17.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_locations".tr, style: theme.textTheme.labelLarge), Text("lbl_edit_locations".tr, style: CustomTextStyles.bodySmallPrimary12)]), SizedBox(height: 9.v), Divider(), SizedBox(height: 13.v), _buildDubaiPlazaNavLink(dubaiPlaza: "lbl_beverly_center".tr, onTapDubaiPlazaNavLink: () {onTapNavLink();}), SizedBox(height: 16.v), Divider(), SizedBox(height: 18.v), _buildDubaiPlazaNavLink(dubaiPlaza: "lbl_dubai_plaza".tr, onTapDubaiPlazaNavLink: () {onTapDubaiPlazaNavLink();}), SizedBox(height: 17.v), Divider(), SizedBox(height: 18.v), _buildDubaiPlazaNavLink(dubaiPlaza: "lbl_kent_utah".tr, onTapDubaiPlazaNavLink: () {onTapNavLink1();})])); } 
/// Section Widget
Widget _buildCheckbox() { return Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Obx(() => CustomCheckboxButton(alignment: Alignment.centerLeft, text: "msg_continue_selling".tr, value: controller.checkbox.value, padding: EdgeInsets.symmetric(vertical: 1.v), onChange: (value) {controller.checkbox.value = value;})))); } 
/// Section Widget
Widget _buildHasSkuOrBarcode() { return Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Obx(() => CustomCheckboxButton(alignment: Alignment.centerLeft, text: "msg_this_product_has".tr, value: controller.hasSkuOrBarcode.value, padding: EdgeInsets.symmetric(vertical: 1.v), onChange: (value) {controller.hasSkuOrBarcode.value = value;})))); } 
/// Common widget
Widget _buildDubaiPlazaNavLink({required String dubaiPlaza, Function? onTapDubaiPlazaNavLink, }) { return GestureDetector(onTap: () {onTapDubaiPlazaNavLink!.call();}, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgMapPin, height: 14.adaptSize, width: 14.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h), child: Text(dubaiPlaza, style: CustomTextStyles.bodyMediumGray600.copyWith(color: appTheme.gray600))), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 16.adaptSize, width: 16.adaptSize)])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the setVariantsScreen when the action is triggered.
onTapBtnEdit() { Get.toNamed(AppRoutes.setVariantsScreen, ); } 
/// Navigates to the bottomMenuOneScreen when the action is triggered.
onTapNavLink() { Get.toNamed(AppRoutes.bottomMenuOneScreen, ); } 
/// Navigates to the bottomMenuOneScreen when the action is triggered.
onTapDubaiPlazaNavLink() { Get.toNamed(AppRoutes.bottomMenuOneScreen, ); } 
/// Navigates to the bottomMenuOneScreen when the action is triggered.
onTapNavLink1() { Get.toNamed(AppRoutes.bottomMenuOneScreen, ); } 
/// Navigates to the createProductVariantsScreen when the action is triggered.
onTapSaveNext() { Get.toNamed(AppRoutes.createProductVariantsScreen, ); } 
/// Navigates to the createProductProductInfoTabContainerScreen when the action is triggered.
onTapBack() { Get.toNamed(AppRoutes.createProductProductInfoTabContainerScreen, ); } 
 }
